# Generated by Django 2.1.4 on 2019-05-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_auto_20190524_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='foto',
            field=models.ImageField(blank=True, default='web/2.jpeg', null=True, upload_to='servicios'),
        ),
    ]
