# Generated by Django 2.1.4 on 2019-05-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='servicios'),
        ),
    ]
