# Generated by Django 2.0 on 2018-07-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberos', '0002_cuenta_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='tipo',
            field=models.CharField(choices=[('A', 'Ahorro'), ('C', 'Corriente')], max_length=1),
        ),
    ]
