# Generated by Django 2.1.7 on 2019-04-27 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Barbero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('apodo', models.CharField(max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=15)),
                ('barbero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barberos.Barbero')),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=22, unique=True)),
                ('tipo', models.CharField(choices=[('A', 'Ahorro'), ('C', 'Corriente')], max_length=1)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barberos.Banco')),
                ('barbero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barberos.Barbero')),
            ],
        ),
    ]
